// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgjfowqydeivwhhviwok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnamZvd3F5ZGVpdndoaHZpd29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMjQ2MTksImV4cCI6MjA2MzgwMDYxOX0.AAaFYorcsWSLpo8T9qxtwjLJGJhcG-iQjmYYK594j6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);